---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-hello-world
  namespace: default
  labels:
    app.kubernetes.io/name: flask-hello-world
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: flask-hello-world
  template:
    metadata:
      labels:
        app.kubernetes.io/name: flask-hello-world
    spec:
      containers:
        - name: flask-hello-world
          image: "cloudysystem/flask-hello-world:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources: {}
