---
apiVersion: v1
kind: Service
metadata:
  name: flask-hello-world
  labels:
    app.kubernetes.io/name: flask-hello-world
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: flask-hello-world
  ports:
    - port: 5000
      targetPort: http
      protocol: TCP
      name: http
